spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          gitlab:
            client-id: ${GITLAB_CLIENT_ID}
            client-secret: ${GITLAB_CLIENT_SECRET}
            client-name: ${GITLAB_CLIENT_NAME}
            redirect-uri: ${GITLAB_REDIRECT_URI}
            authorization-grant-type: ${GITLAB_AUTHORIZATION_GRANT_TYPE}
        provider:
          gitlab:
            authorization-uri: ${GITLAB_AUTHORIZATION_URI}
            token-uri: ${GITLAB_TOKEN_URI}
            user-info-uri: ${GITLAB_USER_INFO_URI}

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}